---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geodb
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: downloader
  namespace: traefik
spec:
  template:
    spec:
      containers:
      - name: downloader
        image: alpine/curl
        args: ["-OL", "--output-dir", "/tmp/", "https://git.io/GeoLite2-Country.mmdb"]
        volumeMounts:
          - mountPath: /tmp
            name: geodb
      volumes:
        - name: geodb
          persistentVolumeClaim:
            claimName: geodb
      restartPolicy: Never
  backoffLimit: 4